<a href="https://colab.research.google.com/github/hobbsandbobs-dotcom/Analytics-Coursework/blob/main/4_Mongo_DB_Section.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. MongoDB Set up

In [2]:
# Installing MongoDB dependencies required for Atlas connectivity
!pip install pymongo dnspython

import pandas as pd
import os

from pymongo import MongoClient

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.6 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 18.1 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [3]:
os.environ["mongo_details"] = "mongodb+srv://iona01hobbs_db_user:NNjYkznb9t724OTW@analyticsassignment.wtcaefz.mongodb.net/?appName=AnalyticsAssignment"

northstar_atlas_assign = os.getenv("mongo_details")

hosting = MongoClient(northstar_atlas_assign)

In [4]:
hosting.admin.command("ping")

#Checking that the authentication was a success

{'ok': 1}

In [5]:
db = hosting["northstar_operational_interactions"]

#Naming the MongoDB database

In [6]:
#Defining the new MongoDB collection objects


integrated_services_coll = db["integrated_lifecycles"]

infrastructure_coll = db["infrastructure_hubs"]

platform_activity_coll = db["digital_events"]

clientele_coll = db["customers_accounts"]

workforce_coll = db["workforce_assets"]

resolution_cases_coll = db["recovering_services"]

fleet_coll = db["fleet_assets"]

In [7]:
from google.colab import files

uploaded = files.upload()

Saving vehicles_clean.csv to vehicles_clean.csv
Saving orders_clean.csv to orders_clean.csv
Saving incidents_clean.csv to incidents_clean.csv
Saving hubs_clean.csv to hubs_clean.csv
Saving drivers_clean.csv to drivers_clean.csv
Saving deliveries_clean.csv to deliveries_clean.csv
Saving customers_clean.csv to customers_clean.csv
Saving complaints_clean.csv to complaints_clean.csv
Saving app_events_clean.csv to app_events_clean.csv

In [8]:
#Reloading the cleaned datasets
orders_df = pd.read_csv("orders_clean.csv")
deliveries_df = pd.read_csv("deliveries_clean.csv")
incidents_df = pd.read_csv("incidents_clean.csv")
complaints_df = pd.read_csv("complaints_clean.csv")
customers_df = pd.read_csv("customers_clean.csv")
app_events_df = pd.read_csv("app_events_clean.csv")
drivers_df = pd.read_csv("drivers_clean.csv")
vehicles_df = pd.read_csv("vehicles_clean.csv")
hubs_df = pd.read_csv("hubs_clean.csv")

In [9]:
#Converting the df into MongoDB records

records_orders = orders_df.to_dict("records")

records_deliveries = deliveries_df.to_dict("records")

records_hubs = hubs_df.to_dict("records")

records_incidents = incidents_df.to_dict("records")

records_complaints = complaints_df.to_dict("records")

records_drivers = drivers_df.to_dict("records")

records_customers = customers_df.to_dict("records")

records_app_events = app_events_df.to_dict("records")

records_vehicles = vehicles_df.to_dict("records")

2. Designing the documents

In [108]:
nstar_service_operations = []

#Creates nstar service operations

In [109]:

for document_index in range(20):

    order_record_tst = orders_df.iloc[document_index]

    order_record_id_tst = order_record_tst["order_id"]

    delivery_related = deliveries_df[
        deliveries_df["order_id"] == order_record_id_tst
    ]

    if delivery_related.empty:

        continue

    complaints_related = complaints_df[
        complaints_df["order_id"] == order_record_id_tst
    ]

    app_events_related = app_events_df[
        app_events_df["order_id"] == order_record_id_tst
    ]

    delivery_id_tst = delivery_related.iloc[0]["delivery_id"]

    incidents_related = incidents_df[
        incidents_df["delivery_id"] == delivery_id_tst
    ]

    id_hub_tst = delivery_related.iloc[0]["hub_id"]

    id_vehicle_tst = delivery_related.iloc[0]["vehicle_id"]

    id_driver_tst = delivery_related.iloc[0]["driver_id"]


    driver_related = drivers_df[
        drivers_df["driver_id"] == id_driver_tst
    ]

    hub_related = hubs_df[
        hubs_df["hub_id"] == id_hub_tst
    ]

    vehicle_related = vehicles_df[
        vehicles_df["vehicle_id"] == id_vehicle_tst
    ]

In [110]:


    lifecycle_timeline = [

        {
            "event_stage": "The order was created at:",
            "timestamp": order_record_tst["order_created_at"]
        },

        {
            "event_stage": "The delivery was dispatched at:",
            "timestamp": delivery_related.iloc[0]["dispatch_time"]
        }

    ]

    operational_case_document = {

        "order": order_record_tst.to_dict(),

        "delivery": delivery_related.to_dict("records"),

        "driver": driver_related.to_dict("records"),

        "fleet_asset": vehicle_related.to_dict("records"),

        "infrastructure_hub": hub_related.to_dict("records"),

        "complaints": complaints_related.to_dict("records"),

        "incidents": incidents_related.to_dict("records"),

        "digital_events": app_events_related.to_dict("records"),

        "timeline_events": lifecycle_timeline,

        "lifecycle_flags": {

            "delivery_present":
                bool(not delivery_related.empty),

            "digi_activity_present":
                bool(not app_events_related.empty),

            "incident_present":
                bool(not incidents_related.empty),

            "complaint_present":
                bool(not complaints_related.empty),


            "completion_proof_null": bool(
                delivery_related.iloc[0][
                    "proof_of_completion_missing"
                ] == 1
            ),


            "increased_overrides": bool(
                delivery_related.iloc[0][
                    "manual_route_override_count"
                ] >= 1
            )


        },

        "ops_recovery_status": {

            "delivery_status":
                delivery_related.iloc[0]["delivery_status"],

            "recovery_support_needed":
                bool(
                    not incidents_related.empty
                    or not complaints_related.empty
                ),

            "impacted_customer_present":
                bool(not complaints_related.empty),

            "delivery_issue_flagged":
                bool(
                    delivery_related.iloc[0][
                        "delivery_status"
                    ] != "OnTime"
                )
        },

        "observations_from_incident": [

            {
                "note_type":
                    "Review of the coordination across our NorthStar lifecycle",

                "description":
                    "Record generated to help with multi and cross system views and associated recovery efforts"
            }
        ]
    }

In [111]:
    nstar_service_operations.append(
        operational_case_document
    )

CREATE

In [71]:
integrated_services_coll.delete_many({})

DeleteResult({'n': 1, 'electionId': ObjectId('7fffffff000000000000010e'), 'opTime': {'ts': Timestamp(1779383953, 36), 't': 270}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1779383953, 36), 'signature': {'hash': b'\xd9\x1c\xfc\xae)\xdc\x8d|J\xc7I\x93\x10Pg\x0e\x1b\xf1G\x99', 'keyId': 7598216932432543809}}, 'operationTime': Timestamp(1779383953, 36)}, acknowledged=True)

In [112]:
integrated_services_coll.insert_many(
    nstar_service_operations
)

InsertManyResult([ObjectId('6a0f3f23431f90ecb6d73b96')], acknowledged=True)

In [113]:
#Checking the above worked

integrated_services_coll.count_documents({})

7

In [115]:
order_record_id_tst = nstar_service_operations[0][
    "order"
]["order_id"]

#This takes the first document from the list

In [116]:
print(order_record_id_tst)

O00020

In [18]:
clientele_coll.delete_many({})

clientele_coll.insert_many(records_customers)

print(
    "Successful"
)

#Checking documents can be inserted into the other collections made at the start

Successful

In [117]:
clientele_coll.count_documents({})

650

READ

In [124]:
#Read operation

retrieved_document = (
    integrated_services_coll.find_one()
)

In [125]:
retrieved_document

#Expected output is a nested long document
#Validating that the nested record can be retrieved

{'_id': ObjectId('6a0f3ea2431f90ecb6d73b90'),
 'order': {'order_id': 'O00020',
  'customer_id': 'C0249',
  'service_type': 'Retail',
  'order_created_at': '2024-05-09 22:25:00',
  'promised_window_hours': 2,
  'pickup_zone': 'West',
  'dropoff_zone': 'Airport',
  'priority_level': 'Medium',
  'order_value': 100.78,
  'booking_channel': 'App',
  'special_handling_flag': 0},
 'delivery': [{'delivery_id': 'DL00752',
   'order_id': 'O00020',
   'driver_id': 'D069',
   'vehicle_id': 'V013',
   'hub_id': 'H01',
   'dispatch_time': '2024-05-09 23:04:00',
   'delivery_completed_at': '2024-05-09 22:49:00.000000',
   'delivery_status': 'OnTime',
   'route_distance_km': 12.27,
   'manual_route_override_count': 1,
   'proof_of_completion_missing': 0,
   'customer_rating_post_delivery': 4.33,
   'fuel_or_charge_cost': 8.63,
   'delivery_complete_flag': True,
   'rating_recorded_flag': True,
   'deliv_complete_at_flag': True,
   'deliv_rating_recorded_flag': True}],
 'driver': [{'driver_id': 'D069',
   'base_zone': 'North',
   'employment_type': 'PartTime',
   'years_experience': 2,
   'training_score': 61.5,
   'driver_rating': 5.0,
   'shift_preference': 'Evening',
   'active_flag': 0,
   'missing_training_flag': False}],
 'fleet_asset': [{'vehicle_id': 'V013',
   'vehicle_type': 'CargoVan',
   'assigned_zone': 'West',
   'commission_date': '2025-07-17 18:07:00',
   'battery_health_pct': 68.3,
   'odometer_km': 153106,
   'maintenance_status': 'Scheduled',
   'telematics_version': 'v2.0',
   'battery_health_missing': False}],
 'infrastructure_hub': [{'hub_id': 'H01',
   'hub_name': 'North Exchange',
   'zone': 'North',
   'hub_type': 'Dispatch',
   'capacity_score': 82}],
 'complaints': [],
 'incidents': [],
 'digital_events': [{'event_id': 'AE00147',
   'customer_id': 'C0128',
   'order_id': 'O00020',
   'event_timestamp': '2024-09-28 14:16:00',
   'event_type': 'track_order',
   'session_id': 'S54633',
   'device_type': 'iOS',
   'zone_context': 'Central',
   'api_latency_ms': 836,
   'success_flag': 1,
   'order_recorded_flag': True}],
 'timeline_events': [{'event_stage': 'The order was created at:',
   'timestamp': '2024-05-09 22:25:00'},
  {'event_stage': 'The delivery was dispatched at:',
   'timestamp': '2024-05-09 23:04:00'}],
 'lifecycle_flags': {'delivery_present': True,
  'digi_activity_present': True,
  'incident_present': False,
  'complaint_present': False,
  'completion_proof_null': False,
  'increased_overrides': True},
 'ops_recovery_status': {'delivery_status': 'OnTime',
  'recovery_support_needed': False,
  'impacted_customer_present': False,
  'delivery_issue_flagged': False},
 'observations_from_incident': [{'note_type': 'Review of the coordination across our NorthStar lifecycle',
   'description': 'Record generated to help with multi and cross system views and associated recovery efforts'}]}

In [127]:
checking_complaints = integrated_services_coll.find({

    "lifecycle_flags.complaint_present": True

})

for found in checking_complaints:

    print(found)

In [128]:
retrieved_document = (
    integrated_services_coll.find_one()
)

print(
    retrieved_document["lifecycle_flags"]
)

{'delivery_present': True, 'digi_activity_present': True, 'incident_present': False, 'complaint_present': False, 'completion_proof_null': False, 'increased_overrides': True}

In [24]:
platform_activity_coll.find_one(

    {},

    {

        "_id": 0,

        "event_type": 1,

        "api_latency_ms": 1,

        "success_flag": 1
    }
)

In [131]:

system_interaction_events = list(

    integrated_services_coll.find(

        {

            "lifecycle_flags.digi_activity_present": True

        },

        {

            "_id": 0,

            "order.booking_channel": 1,

            "order.order_id": 1,

            "delivery.delivery_status": 1,

            "digital_events.event_type": 1,

            "lifecycle_flags.digi_activity_present": 1
        }

    ).limit(15)
)

system_interaction_events

[{'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}},
 {'order': {'order_id': 'O00020', 'booking_channel': 'App'},
  'delivery': [{'delivery_status': 'OnTime'}],
  'digital_events': [{'event_type': 'track_order'}],
  'lifecycle_flags': {'digi_activity_present': True}}]

In [132]:
integrated_services_coll.find_one(

    {},

    {
        "_id": 0,
        "lifecycle_flags": 1
    }
)

{'lifecycle_flags': {'delivery_present': True,
  'digi_activity_present': True,
  'incident_present': False,
  'complaint_present': False,
  'completion_proof_null': False,
  'increased_overrides': True}}

UPDATE Operations

In [137]:

integrated_services_coll.update_one(

    {
        "order.order_id": order_record_id_tst
    },

    {
        "$push": {

            "observations_from_incident": {

                "priority":
                "Critical",

                "immediate_actions":
                "Call customer",

                "note_type":
                "Service escalation",

                "description":
                    "Assessment was undertaken due to a detection of disruption.",

                "resolution_owner":
                    "IT Team",

                "name":
                    "John Doe"

            }
        }
    }
)

UpdateResult({'n': 1, 'electionId': ObjectId('7fffffff000000000000010e'), 'opTime': {'ts': Timestamp(1779387697, 73), 't': 270}, 'nModified': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1779387697, 73), 'signature': {'hash': b'2\xc5]<F\x92\xc1\x1c\xce>1\x07\x15_E9\xf8\xb5+H', 'keyId': 7598216932432543809}}, 'operationTime': Timestamp(1779387697, 73), 'updatedExisting': True}, acknowledged=True)

In [140]:
updated_document = integrated_services_coll.find_one({

    "order.order_id": order_record_id_tst

})

print(updated_document["observations_from_incident"])

[{'note_type': 'Review of the coordination across our NorthStar lifecycle', 'description': 'Record generated to help with multi and cross system views and associated recovery efforts'}, {'note_type': 'Service escalation', 'description': 'A customer recovery assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}, {'priority': 'Critical', 'immediate_actions': 'Call customer', 'note_type': 'Service escalation', 'description': 'Assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}, {'priority': 'Critical', 'immediate_actions': 'Call customer', 'note_type': 'Service escalation', 'description': 'Assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}]

In [144]:
integrated_services_coll.update_one(

    {

        "order.order_id": order_record_id_tst
    },

    {

        "$set": {

            "ops_recovery_status.recovery_support_needed": True,

            "ops_recovery_status.escalation_required_slt": True,

            "ops_recovery_status.delivery_issue_flagged": True,

            "ops_recovery_status.recovery_review_reason":
                "Service issue: triggered escalation."
        }
    }
)

UpdateResult({'n': 1, 'electionId': ObjectId('7fffffff000000000000010e'), 'opTime': {'ts': Timestamp(1779387969, 19), 't': 270}, 'nModified': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1779387969, 19), 'signature': {'hash': b'\xa4 q{\x95\x80\x07)\xbe\x152\x04\x86ObJh#\xfd\xda', 'keyId': 7598216932432543809}}, 'operationTime': Timestamp(1779387969, 19), 'updatedExisting': True}, acknowledged=True)

In [145]:
check_updated = integrated_services_coll.find_one(

    {

        "order.order_id": order_record_id_tst
    }
)

print(

    check_updated["ops_recovery_status"]
)

{'delivery_status': 'OnTime', 'recovery_support_needed': True, 'impacted_customer_present': False, 'delivery_issue_flagged': True, 'recovery_review_reason': 'Service issue: triggered escalation.', 'escalation_required_slt': True}

DELETE

In [31]:

integrated_services_coll.delete_one(

    {
        "order.order_id": order_record_id_tst
    }
)

DeleteResult({'n': 1, 'electionId': ObjectId('7fffffff000000000000010e'), 'opTime': {'ts': Timestamp(1779383422, 33), 't': 270}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1779383422, 34), 'signature': {'hash': b'\x82\xe3\xc2)n\xdd\xc0\x98bUe\xab\xd0\xb2sY\x80\xf5!\x84', 'keyId': 7598216932432543809}}, 'operationTime': Timestamp(1779383422, 33)}, acknowledged=True)

In [174]:
crud_delete_document = integrated_services_coll.find_one({

    "order.order_id": order_record_id_tst
})

print(crud_delete_document)

{'_id': ObjectId('6a0f3ea2431f90ecb6d73b90'), 'order': {'order_id': 'O00020', 'customer_id': 'C0249', 'service_type': 'Retail', 'order_created_at': '2024-05-09 22:25:00', 'promised_window_hours': 2, 'pickup_zone': 'West', 'dropoff_zone': 'Airport', 'priority_level': 'Medium', 'order_value': 100.78, 'booking_channel': 'App', 'special_handling_flag': 0}, 'delivery': [{'delivery_id': 'DL00752', 'order_id': 'O00020', 'driver_id': 'D069', 'vehicle_id': 'V013', 'hub_id': 'H01', 'dispatch_time': '2024-05-09 23:04:00', 'delivery_completed_at': '2024-05-09 22:49:00.000000', 'delivery_status': 'OnTime', 'route_distance_km': 12.27, 'manual_route_override_count': 1, 'proof_of_completion_missing': 0, 'customer_rating_post_delivery': 4.33, 'fuel_or_charge_cost': 8.63, 'delivery_complete_flag': True, 'rating_recorded_flag': True, 'deliv_complete_at_flag': True, 'deliv_rating_recorded_flag': True}], 'driver': [{'driver_id': 'D069', 'base_zone': 'North', 'employment_type': 'PartTime', 'years_experience': 2, 'training_score': 61.5, 'driver_rating': 5.0, 'shift_preference': 'Evening', 'active_flag': 0, 'missing_training_flag': False}], 'fleet_asset': [{'vehicle_id': 'V013', 'vehicle_type': 'CargoVan', 'assigned_zone': 'West', 'commission_date': '2025-07-17 18:07:00', 'battery_health_pct': 68.3, 'odometer_km': 153106, 'maintenance_status': 'Scheduled', 'telematics_version': 'v2.0', 'battery_health_missing': False}], 'infrastructure_hub': [{'hub_id': 'H01', 'hub_name': 'North Exchange', 'zone': 'North', 'hub_type': 'Dispatch', 'capacity_score': 82}], 'complaints': [], 'incidents': [], 'digital_events': [{'event_id': 'AE00147', 'customer_id': 'C0128', 'order_id': 'O00020', 'event_timestamp': '2024-09-28 14:16:00', 'event_type': 'track_order', 'session_id': 'S54633', 'device_type': 'iOS', 'zone_context': 'Central', 'api_latency_ms': 836, 'success_flag': 1, 'order_recorded_flag': True}], 'timeline_events': [{'event_stage': 'The order was created at:', 'timestamp': '2024-05-09 22:25:00'}, {'event_stage': 'The delivery was dispatched at:', 'timestamp': '2024-05-09 23:04:00'}], 'lifecycle_flags': {'delivery_present': True, 'digi_activity_present': True, 'incident_present': False, 'complaint_present': False, 'completion_proof_null': False, 'increased_overrides': True}, 'ops_recovery_status': {'delivery_status': 'OnTime', 'recovery_support_needed': True, 'impacted_customer_present': False, 'delivery_issue_flagged': True, 'recovery_review_reason': 'Service issue: triggered escalation.', 'escalation_required_slt': True}, 'observations_from_incident': [{'note_type': 'Review of the coordination across our NorthStar lifecycle', 'description': 'Record generated to help with multi and cross system views and associated recovery efforts'}, {'note_type': 'Service escalation', 'description': 'A customer recovery assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}, {'priority': 'Critical', 'immediate_actions': 'Call customer', 'note_type': 'Service escalation', 'description': 'Assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}, {'priority': 'Critical', 'immediate_actions': 'Call customer', 'note_type': 'Service escalation', 'description': 'Assessment was undertaken due to a detection of disruption.', 'resolution_owner': 'IT Team', 'name': 'John Doe'}]}

AGGREGATION

In [185]:
nstar_post_incident_summary = [


    {
        "$unwind": "$digital_events"
    },

    {
        "$match": {


            "lifecycle_flags.digi_activity_present": True,

            "digital_events.api_latency_ms": {

                "$gte": 200
            }
        }
    },

    {
        "$group": {

            "_id": {

                "booking_channel":
                    "$order.booking_channel",

                "event_type":
                    "$digital_events.event_type"
            },

            "volume_of_events": {

                "$sum": 1

            },

            "average_response_time": {
                "$avg":
                    "$digital_events.api_latency_ms"
            },

            "customer_issue_events": {

                "$sum": {

                    "$cond": [

                        "$lifecycle_flags.complaint_present",
                        1,
                        0
                    ]

                }
            },

            "service_incident_events": {

                "$sum": {

                    "$cond": [

                        "$ops_recovery_status.delivery_issue_flagged",
                        1,
                        0
                    ]
                }

            },

            "driver_route_event": {

                "$sum": {

                    "$cond": [

                        "$lifecycle_flags.increased_overrides",
                        1,
                        0
                    ]
                }
            }
        }

    },

    {
        "$project": {

            "_id": 0,

            "booking_channel":
                "$_id.booking_channel",

            "event_type":
                "$_id.event_type",

            "volume_of_events": 1,

            "average_response_time": {
                "$round": [
                    "$average_response_time",
                    2
                ]

            },

            "amt_customer_issue": {

                "$round": [

                    {
                        "$multiply": [

                            {
                                "$divide": [

                                    "$customer_issue_events",
                                    "$volume_of_events"
                                ]
                            },

                            100
                        ]
                    },

                    2

                ]
            },


            "customer_issue_events": 1,


            "service_incident_events": 1,



            "driver_route_event": 1
        }
    },

    {
        "$sort": {

            "service_incident_events": -1,

            "amt_customer_issue": -1,

            "average_response_time": -1
        }
    }
]

performance_outputs = list(

    integrated_services_coll.aggregate(

        nstar_post_incident_summary


    )
)

digital_master_dataset = pd.DataFrame(

    performance_outputs

)

digital_master_dataset

,volume_of_events,customer_issue_events,service_incident_events,driver_route_event,booking_channel,event_type,average_response_time,amt_customer_issue
0,7,0,1,7,App,track_order,836.0,0.0

In [178]:
integrated_services_coll.find(

    {

        "lifecycle_flags.digi_activity_present": True,

        "ops_recovery_status.delivery_issue_flagged": True,

        "digital_events.api_latency_ms": {
            "$gte": 200
        }
    }

).explain()

{'explainVersion': '1',
 'queryPlanner': {'namespace': 'northstar_operational_interactions.integrated_lifecycles',
  'parsedQuery': {'$and': [{'lifecycle_flags.digi_activity_present': {'$eq': True}},
    {'ops_recovery_status.delivery_issue_flagged': {'$eq': True}},
    {'digital_events.api_latency_ms': {'$gte': 200}}]},
  'indexFilterSet': False,
  'queryHash': '57A5AFDC',
  'planCacheShapeHash': '57A5AFDC',
  'planCacheKey': '078DFEA7',
  'optimizationTimeMillis': 0,
  'maxIndexedOrSolutionsReached': False,
  'maxIndexedAndSolutionsReached': False,
  'maxScansToExplodeReached': False,
  'prunedSimilarIndexes': False,
  'winningPlan': {'isCached': False,
   'stage': 'FETCH',
   'filter': {'$and': [{'digital_events.api_latency_ms': {'$gte': 200}},
     {'lifecycle_flags.digi_activity_present': {'$eq': True}}]},
   'inputStage': {'stage': 'IXSCAN',
    'keyPattern': {'ops_recovery_status.delivery_issue_flagged': 1,
     'ops_recovery_status.impacted_customer_present': 1,
     'ops_recovery_status.recovery_support_needed': 1},
    'indexName': 'ops_recovery_status.delivery_issue_flagged_1_ops_recovery_status.impacted_customer_present_1_ops_recovery_status.recovery_support_needed_1',
    'isMultiKey': False,
    'multiKeyPaths': {'ops_recovery_status.delivery_issue_flagged': [],
     'ops_recovery_status.impacted_customer_present': [],
     'ops_recovery_status.recovery_support_needed': []},
    'isUnique': False,
    'isSparse': False,
    'isPartial': False,
    'indexVersion': 2,
    'direction': 'forward',
    'indexBounds': {'ops_recovery_status.delivery_issue_flagged': ['[true, true]'],
     'ops_recovery_status.impacted_customer_present': ['[MinKey, MaxKey]'],
     'ops_recovery_status.recovery_support_needed': ['[MinKey, MaxKey]']}}},
  'rejectedPlans': [{'isCached': False,
    'stage': 'FETCH',
    'filter': {'digital_events.api_latency_ms': {'$gte': 200}},
    'inputStage': {'stage': 'IXSCAN',
     'keyPattern': {'lifecycle_flags.digi_activity_present': 1,
      'lifecycle_flags.complaint_present': 1,
      'ops_recovery_status.delivery_issue_flagged': 1,
      'digital_events.event_type': 1},
     'indexName': 'lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1_digital_events.event_type_1',
     'isMultiKey': True,
     'multiKeyPaths': {'lifecycle_flags.digi_activity_present': [],
      'lifecycle_flags.complaint_present': [],
      'ops_recovery_status.delivery_issue_flagged': [],
      'digital_events.event_type': ['digital_events']},
     'isUnique': False,
     'isSparse': False,
     'isPartial': False,
     'indexVersion': 2,
     'direction': 'forward',
     'indexBounds': {'lifecycle_flags.digi_activity_present': ['[true, true]'],
      'lifecycle_flags.complaint_present': ['[MinKey, MaxKey]'],
      'ops_recovery_status.delivery_issue_flagged': ['[true, true]'],
      'digital_events.event_type': ['[MinKey, MaxKey]']}}}]},
 'executionStats': {'executionSuccess': True,
  'nReturned': 1,
  'executionTimeMillis': 0,
  'totalKeysExamined': 1,
  'totalDocsExamined': 1,
  'executionStages': {'isCached': False,
   'stage': 'FETCH',
   'filter': {'$and': [{'digital_events.api_latency_ms': {'$gte': 200}},
     {'lifecycle_flags.digi_activity_present': {'$eq': True}}]},
   'nReturned': 1,
   'executionTimeMillisEstimate': 0,
   'works': 3,
   'advanced': 1,
   'needTime': 0,
   'needYield': 0,
   'saveState': 0,
   'restoreState': 0,
   'isEOF': 1,
   'docsExamined': 1,
   'alreadyHasObj': 0,
   'inputStage': {'stage': 'IXSCAN',
    'nReturned': 1,
    'executionTimeMillisEstimate': 0,
    'works': 2,
    'advanced': 1,
    'needTime': 0,
    'needYield': 0,
    'saveState': 0,
    'restoreState': 0,
    'isEOF': 1,
    'keyPattern': {'ops_recovery_status.delivery_issue_flagged': 1,
     'ops_recovery_status.impacted_customer_present': 1,
     'ops_recovery_status.recovery_support_needed': 1},
    'indexName': 'ops_recovery_status.delivery_issue_flagged_1_ops_recovery_status.impacted_customer_present_1_ops_recovery_status.recovery_support_needed_1',
    'isMultiKey': False,
    'multiKeyPaths': {'ops_recovery_status.delivery_issue_flagged': [],
     'ops_recovery_status.impacted_customer_present': [],
     'ops_recovery_status.recovery_support_needed': []},
    'isUnique': False,
    'isSparse': False,
    'isPartial': False,
    'indexVersion': 2,
    'direction': 'forward',
    'indexBounds': {'ops_recovery_status.delivery_issue_flagged': ['[true, true]'],
     'ops_recovery_status.impacted_customer_present': ['[MinKey, MaxKey]'],
     'ops_recovery_status.recovery_support_needed': ['[MinKey, MaxKey]']},
    'keysExamined': 1,
    'seeks': 1,
    'dupsTested': 0,
    'dupsDropped': 0}},
  'allPlansExecution': [{'nReturned': 1,
    'executionTimeMillisEstimate': 0,
    'totalKeysExamined': 1,
    'totalDocsExamined': 1,
    'score': 2.5002,
    'executionStages': {'isCached': False,
     'stage': 'FETCH',
     'filter': {'$and': [{'digital_events.api_latency_ms': {'$gte': 200}},
       {'lifecycle_flags.digi_activity_present': {'$eq': True}}]},
     'nReturned': 1,
     'executionTimeMillisEstimate': 0,
     'works': 2,
     'advanced': 1,
     'needTime': 0,
     'needYield': 0,
     'saveState': 0,
     'restoreState': 0,
     'isEOF': 1,
     'docsExamined': 1,
     'alreadyHasObj': 0,
     'inputStage': {'stage': 'IXSCAN',
      'nReturned': 1,
      'executionTimeMillisEstimate': 0,
      'works': 2,
      'advanced': 1,
      'needTime': 0,
      'needYield': 0,
      'saveState': 0,
      'restoreState': 0,
      'isEOF': 1,
      'keyPattern': {'ops_recovery_status.delivery_issue_flagged': 1,
       'ops_recovery_status.impacted_customer_present': 1,
       'ops_recovery_status.recovery_support_needed': 1},
      'indexName': 'ops_recovery_status.delivery_issue_flagged_1_ops_recovery_status.impacted_customer_present_1_ops_recovery_status.recovery_support_needed_1',
      'isMultiKey': False,
      'multiKeyPaths': {'ops_recovery_status.delivery_issue_flagged': [],
       'ops_recovery_status.impacted_customer_present': [],
       'ops_recovery_status.recovery_support_needed': []},
      'isUnique': False,
      'isSparse': False,
      'isPartial': False,
      'indexVersion': 2,
      'direction': 'forward',
      'indexBounds': {'ops_recovery_status.delivery_issue_flagged': ['[true, true]'],
       'ops_recovery_status.impacted_customer_present': ['[MinKey, MaxKey]'],
       'ops_recovery_status.recovery_support_needed': ['[MinKey, MaxKey]']},
      'keysExamined': 1,
      'seeks': 1,
      'dupsTested': 0,
      'dupsDropped': 0}}},
   {'nReturned': 1,
    'executionTimeMillisEstimate': 0,
    'totalKeysExamined': 2,
    'totalDocsExamined': 1,
    'score': 1.5002,
    'executionStages': {'isCached': False,
     'stage': 'FETCH',
     'filter': {'digital_events.api_latency_ms': {'$gte': 200}},
     'nReturned': 1,
     'executionTimeMillisEstimate': 0,
     'works': 2,
     'advanced': 1,
     'needTime': 1,
     'needYield': 0,
     'saveState': 1,
     'restoreState': 0,
     'isEOF': 0,
     'docsExamined': 1,
     'alreadyHasObj': 0,
     'inputStage': {'stage': 'IXSCAN',
      'nReturned': 1,
      'executionTimeMillisEstimate': 0,
      'works': 2,
      'advanced': 1,
      'needTime': 1,
      'needYield': 0,
      'saveState': 1,
      'restoreState': 0,
      'isEOF': 0,
      'keyPattern': {'lifecycle_flags.digi_activity_present': 1,
       'lifecycle_flags.complaint_present': 1,
       'ops_recovery_status.delivery_issue_flagged': 1,
       'digital_events.event_type': 1},
      'indexName': 'lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1_digital_events.event_type_1',
      'isMultiKey': True,
      'multiKeyPaths': {'lifecycle_flags.digi_activity_present': [],
       'lifecycle_flags.complaint_present': [],
       'ops_recovery_status.delivery_issue_flagged': [],
       'digital_events.event_type': ['digital_events']},
      'isUnique': False,
      'isSparse': False,
      'isPartial': False,
      'indexVersion': 2,
      'direction': 'forward',
      'indexBounds': {'lifecycle_flags.digi_activity_present': ['[true, true]'],
       'lifecycle_flags.complaint_present': ['[MinKey, MaxKey]'],
       'ops_recovery_status.delivery_issue_flagged': ['[true, true]'],
       'digital_events.event_type': ['[MinKey, MaxKey]']},
      'keysExamined': 2,
      'seeks': 2,
      'dupsTested': 1,
      'dupsDropped': 0}}}]},
 'queryShapeHash': '95E66178972DC3B76B6ED162AA0BFD96D3D10E31C903D0EEE9D0F04C524B670F',
 'command': {'find': 'integrated_lifecycles',
  'filter': {'lifecycle_flags.digi_activity_present': True,
   'ops_recovery_status.delivery_issue_flagged': True,
   'digital_events.api_latency_ms': {'$gte': 200}},
  '$db': 'northstar_operational_interactions'},
 'serverInfo': {'host': 'ac-45qlgwv-shard-00-02.wtcaefz.mongodb.net',
  'port': 27017,
  'version': '8.0.23',
  'gitVersion': 'ccf0d81588377542f00eeecf1b1ffbc095b1eeff'},
 'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
  'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
  'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
  'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
  'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
  'internalQueryProhibitBlockingMergeOnMongoS': 0,
  'internalQueryMaxAddToSetBytes': 104857600,
  'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
  'internalQueryFrameworkControl': 'trySbeRestricted',
  'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
 'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1779393185, 12),
  'signature': {'hash': b'ckn\xbf\xa6\xd4\xeap\xef)\xe364\xb4\xe7^,\xe5\xa75',
   'keyId': 7598216932432543809}},
 'operationTime': Timestamp(1779393185, 12)}

In [180]:
integrated_services_coll.distinct(
    "order.booking_channel"
)

['App']

In [181]:
digital_master_dataset = pd.DataFrame(
    performance_outputs
)

digital_master_dataset = digital_master_dataset.sort_values(

    by=[
        "service_incident_events",
        "amt_customer_issue"
    ],

    ascending=False
)

digital_master_dataset

,volume_of_events,customer_issue_events,service_incident_events,driver_route_event,booking_channel,event_type,average_response_time,amt_customer_issue
0,7,0,1,7,App,track_order,836.0,0.0

INDEXING/OPTIMISATION

In [164]:
monitoring_lifecycle_indx = integrated_services_coll.create_index([

    (
        "digital_events.event_type",
        1
    ),

       (
        "lifecycle_flags.digi_activity_present",
        1
    ),

    (
        "ops_recovery_status.delivery_issue_flagged",
        1
    ),

    (
        "lifecycle_flags.complaint_present",
        1
    )



])

In [165]:
monitoring_lifecycle_indx

'digital_events.event_type_1_lifecycle_flags.digi_activity_present_1_ops_recovery_status.delivery_issue_flagged_1_lifecycle_flags.complaint_present_1'

In [167]:
integrated_services_coll.find(

    {
        "lifecycle_flags.digi_activity_present": True,

        "lifecycle_flags.complaint_present": True
    }

).explain()

{'explainVersion': '1',
 'queryPlanner': {'namespace': 'northstar_operational_interactions.integrated_lifecycles',
  'parsedQuery': {'$and': [{'lifecycle_flags.complaint_present': {'$eq': True}},
    {'lifecycle_flags.digi_activity_present': {'$eq': True}}]},
  'indexFilterSet': False,
  'queryHash': '59AEC83B',
  'planCacheShapeHash': '59AEC83B',
  'planCacheKey': '5477672E',
  'optimizationTimeMillis': 0,
  'maxIndexedOrSolutionsReached': False,
  'maxIndexedAndSolutionsReached': False,
  'maxScansToExplodeReached': False,
  'prunedSimilarIndexes': False,
  'winningPlan': {'isCached': False,
   'stage': 'FETCH',
   'inputStage': {'stage': 'IXSCAN',
    'keyPattern': {'lifecycle_flags.digi_activity_present': 1,
     'lifecycle_flags.complaint_present': 1,
     'ops_recovery_status.delivery_issue_flagged': 1,
     'digital_events.event_type': 1},
    'indexName': 'lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1_digital_events.event_type_1',
    'isMultiKey': True,
    'multiKeyPaths': {'lifecycle_flags.digi_activity_present': [],
     'lifecycle_flags.complaint_present': [],
     'ops_recovery_status.delivery_issue_flagged': [],
     'digital_events.event_type': ['digital_events']},
    'isUnique': False,
    'isSparse': False,
    'isPartial': False,
    'indexVersion': 2,
    'direction': 'forward',
    'indexBounds': {'lifecycle_flags.digi_activity_present': ['[true, true]'],
     'lifecycle_flags.complaint_present': ['[true, true]'],
     'ops_recovery_status.delivery_issue_flagged': ['[MinKey, MaxKey]'],
     'digital_events.event_type': ['[MinKey, MaxKey]']}}},
  'rejectedPlans': []},
 'executionStats': {'executionSuccess': True,
  'nReturned': 0,
  'executionTimeMillis': 0,
  'totalKeysExamined': 0,
  'totalDocsExamined': 0,
  'executionStages': {'isCached': False,
   'stage': 'FETCH',
   'nReturned': 0,
   'executionTimeMillisEstimate': 0,
   'works': 1,
   'advanced': 0,
   'needTime': 0,
   'needYield': 0,
   'saveState': 0,
   'restoreState': 0,
   'isEOF': 1,
   'docsExamined': 0,
   'alreadyHasObj': 0,
   'inputStage': {'stage': 'IXSCAN',
    'nReturned': 0,
    'executionTimeMillisEstimate': 0,
    'works': 1,
    'advanced': 0,
    'needTime': 0,
    'needYield': 0,
    'saveState': 0,
    'restoreState': 0,
    'isEOF': 1,
    'keyPattern': {'lifecycle_flags.digi_activity_present': 1,
     'lifecycle_flags.complaint_present': 1,
     'ops_recovery_status.delivery_issue_flagged': 1,
     'digital_events.event_type': 1},
    'indexName': 'lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1_digital_events.event_type_1',
    'isMultiKey': True,
    'multiKeyPaths': {'lifecycle_flags.digi_activity_present': [],
     'lifecycle_flags.complaint_present': [],
     'ops_recovery_status.delivery_issue_flagged': [],
     'digital_events.event_type': ['digital_events']},
    'isUnique': False,
    'isSparse': False,
    'isPartial': False,
    'indexVersion': 2,
    'direction': 'forward',
    'indexBounds': {'lifecycle_flags.digi_activity_present': ['[true, true]'],
     'lifecycle_flags.complaint_present': ['[true, true]'],
     'ops_recovery_status.delivery_issue_flagged': ['[MinKey, MaxKey]'],
     'digital_events.event_type': ['[MinKey, MaxKey]']},
    'keysExamined': 0,
    'seeks': 1,
    'dupsTested': 0,
    'dupsDropped': 0}},
  'allPlansExecution': []},
 'queryShapeHash': '630F72174D4F8A9A0988A5D9917DB473C878D35D7271488DE26613DCBE387990',
 'command': {'find': 'integrated_lifecycles',
  'filter': {'lifecycle_flags.digi_activity_present': True,
   'lifecycle_flags.complaint_present': True},
  '$db': 'northstar_operational_interactions'},
 'serverInfo': {'host': 'ac-45qlgwv-shard-00-02.wtcaefz.mongodb.net',
  'port': 27017,
  'version': '8.0.23',
  'gitVersion': 'ccf0d81588377542f00eeecf1b1ffbc095b1eeff'},
 'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
  'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
  'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
  'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
  'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
  'internalQueryProhibitBlockingMergeOnMongoS': 0,
  'internalQueryMaxAddToSetBytes': 104857600,
  'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
  'internalQueryFrameworkControl': 'trySbeRestricted',
  'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
 'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1779392177, 10),
  'signature': {'hash': b'\x14\x8e)\xc8ME\xb9\xf8p\xda\xca\x81K\x80\xe1\x83\x15I\xc2\xf1',
   'keyId': 7598216932432543809}},
 'operationTime': Timestamp(1779392177, 10)}

In [168]:
integrated_services_coll.index_information()

{'_id_': {'v': 2, 'key': [('_id', 1)]},
 'operational_case_status.service_exception_detected_1_operational_case_status.customer_impact_detected_1_operational_case_status.resolution_required_1': {'v': 2,
  'key': [('operational_case_status.service_exception_detected', 1),
   ('operational_case_status.customer_impact_detected', 1),
   ('operational_case_status.resolution_required', 1)]},
 'ops_recovery_status.delivery_issue_flagged_1_ops_recovery_status.impacted_customer_present_1_ops_recovery_status.recovery_support_needed_1': {'v': 2,
  'key': [('ops_recovery_status.delivery_issue_flagged', 1),
   ('ops_recovery_status.impacted_customer_present', 1),
   ('ops_recovery_status.recovery_support_needed', 1)]},
 'digital_events.success_flag_1_digital_events.api_latency_ms_-1_ops_recovery_status.delivery_issue_flagged_1': {'v': 2,
  'key': [('digital_events.success_flag', 1),
   ('digital_events.api_latency_ms', -1),
   ('ops_recovery_status.delivery_issue_flagged', 1)]},
 'lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1_digital_events.event_type_1': {'v': 2,
  'key': [('lifecycle_flags.digi_activity_present', 1),
   ('lifecycle_flags.complaint_present', 1),
   ('ops_recovery_status.delivery_issue_flagged', 1),
   ('digital_events.event_type', 1)]},
 'digital_events.event_type_1_lifecycle_flags.digi_activity_present_1_lifecycle_flags.complaint_present_1_ops_recovery_status.delivery_issue_flagged_1': {'v': 2,
  'key': [('digital_events.event_type', 1),
   ('lifecycle_flags.digi_activity_present', 1),
   ('lifecycle_flags.complaint_present', 1),
   ('ops_recovery_status.delivery_issue_flagged', 1)]},
 'digital_events.event_type_1_lifecycle_flags.digi_activity_present_1_ops_recovery_status.delivery_issue_flagged_1_lifecycle_flags.complaint_present_1': {'v': 2,
  'key': [('digital_events.event_type', 1),
   ('lifecycle_flags.digi_activity_present', 1),
   ('ops_recovery_status.delivery_issue_flagged', 1),
   ('lifecycle_flags.complaint_present', 1)]}}